name       : python-scikit-build
version    : 0.16.3
release    : 1
source     :
    - https://files.pythonhosted.org/packages/source/s/scikit-build/scikit-build-0.16.3.tar.gz : 656ecabf264df6e23d103e02f4887c0fe5a47a2cd42f66cf3de08201de0cbf37
homepage   : https://github.com/scikit-build/scikit-build
license    : MIT
component  : programming.python
summary    : Improved build system generator for CPython C, C++, Cython and Fortran extensions
description: |
    Improved build system generator for CPython C/C++/Fortran/Cython extensions.
builddeps  :
    - python-build
    - python-installer
    - python-packaging
    - python-setuptools-scm
rundeps    :
    - python-distro
    - python-packaging
    - python-wheel
build      : |
    %python3_setup
install    : |
    %python3_install
